# Example: Monitoring a system service

[redis]
host = "192.168.1.100"
port = 6379
password = "redis_secret_password"

[app]
executable = "/opt/monitoring/health-checker"
args = ["--interval", "30", "--targets", "web,db,cache"]
user = "monitoring"  # Requires sudo wrapp
stream_name = "health_checker"