name: Update Image Base Submodule

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-submodule:
    name: Update jettison_wrapp in Image Base
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone jettison_image_base repository
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.PUSH_TO_JETTISON_IMAGE_BASE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Clone via SSH (not recursive to avoid trying to clone other private submodules)
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" git clone git@github.com:lpportorino/jettison_image_base.git image-base
          cd image-base

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Update jettison_wrapp submodule to latest commit
          cd jettison_wrapp
          git fetch origin
          git checkout main
          git pull origin main
          cd ..

          # Commit and push if there are changes
          git add jettison_wrapp
          git diff --staged --quiet || {
            git commit -m "Update jettison_wrapp submodule from ${{ github.sha }}"

            # Retry push with rebase if conflicts occur
            MAX_RETRIES=3
            RETRY_COUNT=0

            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" git push; then
                echo "Push succeeded"
                exit 0
              else
                RETRY_COUNT=$((RETRY_COUNT + 1))
                echo "Push failed (attempt $RETRY_COUNT/$MAX_RETRIES)"

                if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                  echo "Rebasing and retrying..."
                  GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" git pull --rebase
                fi
              fi
            done

            echo "Failed to push after $MAX_RETRIES attempts"
            exit 1
          }
